# This is a basic workflow to help you get started with Actions

name: check out and build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: castle6610/andes_build_tools_v323:latest
      # image: 'dockerfile'
        
    steps:
    - uses: actions/checkout@v4.2.1
    
    - name: begin to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        chmod 775 ./build.sh
        ./build.sh build
        python3 ./tools/mva_maker.py -i ./cmake_build/roboeffect_demo.bin -o ./cmake_build/roboeffect_demo.mva
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: build-output
        path: ./cmake_build/
